kalendar_nastave/kalendar_nastave/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("main.urls")),
    path('admin/', admin.site.urls),
]

kalendar_nastave/main/urls.py
from django.urls import path
from . import views
from main.views import VoditeljList, ProstorijaList, RacunaloList
app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('aktivnosti/', views.aktivnosti, name='aktivnosti'),
    path('voditelj/', VoditeljList.as_view()),
    path('prostorija/', ProstorijaList.as_view()),
    path('racunalo/', RacunaloList.as_view()),
]

kalendar_nastave/main/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Voditelj(models.Model):
    ime = models.CharField(max_length=30)
    prezime = models.CharField(max_length=30)
    email = models.EmailField()
    adresa = models.CharField(max_length=100)
    telefon = models.CharField(max_length=20)
    
    def __str__(self):
        return self.prezime

class Racunalo(models.Model):
    id_racunala=models.IntegerField(primary_key=True, default=1)
    marka = models.CharField(max_length=10)
    tip = models.CharField(max_length=20)
    operacijski_sustav = models.CharField(max_length=20)
    mreza = models.BooleanField(default=True)
    
    def __str__(self):
        return "{}, {}".format(self.marka, self.tip)
            
class Prostorija(models.Model):
    broj_prostorije = models.IntegerField(default=1)
    kat = models.IntegerField(default=0)
    naziv_prostorije = models.TextField(default="Prazna dvorana")
    glavno_racunalo = models.OneToOneField(Racunalo, on_delete=models.CASCADE, default=404)
    
    def __str__(self):
        return "{}. kat, Dvorana {}".format(self.kat,self.broj_prostorije)

class Aktivnost(models.Model):
    naziv = models.CharField(max_length=100)
    opis = models.TextField()
    vrijeme_pocetka = models.DateTimeField('Datum početka')
    vrijeme_zavrsetka = models.DateTimeField('Datum planiranog završetka')
    voditelji_aktivnosti = models.ManyToManyField(Voditelj)
    prostorija_izvodjenja = models.ForeignKey(Prostorija, on_delete=models.CASCADE)

    def __str__(self):
         return self.naziv


    
    

kalendar_nastave/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from main.models import Voditelj, Racunalo, Aktivnost, Prostorija
from datetime import datetime
from django import forms

# kalsa za stvaranje forme godina
class YearForm(forms.Form):
    # odabir goidna od 1900 do 2100
    years = [(year, year) for year in range(1900, 2100)]

    # stvaramo ChoiceField 
    Godina_pocetka = forms.ChoiceField(choices=years)

# Create your views here.

class VoditeljList(ListView):
    model=Voditelj
    
class ProstorijaList(ListView):
    model=Prostorija

class RacunaloList(ListView):
    model=Racunalo

def homepage(request):
    return render(request, 'base_generic.html')

def aktivnosti(request):
    current_year = datetime.now().year
    form = YearForm(request.POST or None, initial={'Godina_pocetka': current_year})

    if request.method == 'POST' and form.is_valid():
        # da imamo samo godinu
        year = form.cleaned_data['Godina_pocetka']

        # filtiriranje DateTimeField po godini
        events = Aktivnost.objects.filter(vrijeme_pocetka__date__year=year)
    else:
        events = Aktivnost.objects.all()

    return render(request, 'main/aktivnosti.html', {'form': form, 'events': events})

kalendar_nastave/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
</head>

<body>
    <h1>Kalendar aktivnosti</h1>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/voditelj">Voditelji aktivnosti</a></li>
            <li><a href="/aktivnosti">Aktivnosti</a></li>
            <li><a href="/prostorija">Prostorije</a></li>
            <li><a href="/racunalo">Računala</a></li>
        </ul>
        {% endblock %}
    </div>

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

kalendar_nastave/templates/main/aktivnost_list.html
{% block content %}
    <h2>Aktivnosti</h2>
    <ul>
        {% for aktivnost in object_list %}
            <li>
                Naziv: {{ aktivnost.naziv }}<br>
                Voditelji aktivnosti: <br/>{% for voditelj in aktivnost.voditelji_aktivnosti.all %}{{ voditelj }}<br/>{% endfor %}
                <br>
                Opis: {{ aktivnost.opis }}<br>
                Vrijeme početka: {{ aktivnost.vrijeme_pocetka }}<br>
                Vrijeme planiranog završetka: {{ aktivnost.vrijeme_zavrsetka }}<br>
                Prostorija izvodjenja: {{ aktivnost.prostorija_izvodjenja }}<br>
                <br>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

kalendar_nastave/templates/main/aktivnosti.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>Aktivnosti</h2>
    <form method="POST" action="{% url 'main:aktivnosti' %}">
        {% csrf_token %}
        <!--as_p renderiramo form kao <p>-->
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    <ul>
        {% for aktivnost in events %}
            <li>
                Naziv: {{ aktivnost.naziv }}<br>
                Voditelji aktivnosti: <br/>{% for voditelj in aktivnost.voditelji_aktivnosti.all %}
                    {{ voditelj.ime }} {{ voditelj.prezime }} ({{ voditelj.email }})<br/>{% endfor %}
                <br>
                Opis: {{ aktivnost.opis }}<br>
                Vrijeme početka: {{ aktivnost.vrijeme_pocetka }}<br>
                Vrijeme planiranog završetka: {{ aktivnost.vrijeme_zavrsetka }}<br>
                Prostorija izvodjenja: {{ aktivnost.prostorija_izvodjenja }}<br>
                <br>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

kalendar_nastave/templates/main/prostorija_list.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>Prostorije</h2>
    <ul>
        {% for prostorija in object_list %}
            <li>
                Broj prostorije: {{ prostorija.broj_prostorije }}<br>
                Kat: {{ prostorija.kat }}<br>
                Naziv prostorije: {{ prostorija.naziv_prostorije }}<br>
                Glavno računalo: {{ prostorija.glavno_racunalo }}<br>
                <br>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

kalendar_nastave/templates/main/racunalo_list.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>Računala</h2>
    <ul>
        {% for racunalo in object_list %}
            <li>
                Id: {{ racunalo.id_racunala }}<br>
                Marka: {{ racunalo.marka }}<br>
                Tip: {{ racunalo.tip }}<br>
                Operacijski sustav: {{ racunalo.operacijski_sustav }}<br>
                Spojen na mrežu: {{ racunalo.mreza }}<br>
                <br>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

kalendar_nastave/templates/main/voditelj_list.html
{% extends "base_generic.html" %}
{% block content %}
    <h2>Voditelji</h2>
    <ul>
        {% for voditelj in object_list %}
            <li>
                Ime: {{ voditelj.ime }}<br>
                Prezime: {{ voditelj.prezime }}<br>
                Email: {{ voditelj.email }}<br>
                Adresa: {{ voditelj.adresa }}<br>
                Telefon: {{ voditelj.telefon }}<br>
                <br>
            </li>
        {% endfor %}
    </ul>
{% endblock %}